# Generated by Django 4.2.5 on 2025-04-01 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cross_dept_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='current_ctc',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='expected_ctc',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='requisition',
        ),
        migrations.AddField(
            model_name='candidate',
            name='requisition_no',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='candidate',
            name='current_designation',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='experience',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='phone_no',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.DeleteModel(
            name='RecruitmentFunnel',
        ),
        migrations.DeleteModel(
            name='Requisition',
        ),
        migrations.AddField(
            model_name='candidate',
            name='current_CTC',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidate',
            name='expected_CTC',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
