# Generated by Django 4.2.5 on 2025-04-02 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cross_dept_app', '0004_candidate_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requisition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requisition_no', models.CharField(max_length=20, unique=True)),
                ('department', models.CharField(max_length=100)),
                ('positions', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name='candidate',
            old_name='current_designation',
            new_name='designation',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='current_CTC',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='expected_CTC',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='requisition_no',
        ),
        migrations.AddField(
            model_name='candidate',
            name='remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='experience',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='phone_no',
            field=models.CharField(default=0, max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='candidate',
            name='source',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidate',
            name='current_ctc',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidate',
            name='expected_ctc',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidate',
            name='requisition',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='cross_dept_app.requisition'),
            preserve_default=False,
        ),
    ]
