# Generated by Django 4.2.5 on 2025-04-03 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cross_dept_app', '0005_requisition_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='current_ctc',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='expected_ctc',
            field=models.CharField(max_length=100),
        ),
    ]
