# Generated by Django 4.2.5 on 2025-04-04 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cross_dept_app', '0007_alter_candidate_company_alter_candidate_current_ctc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
