# Generated by Django 4.2.5 on 2025-04-04 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cross_dept_app', '0008_alter_candidate_remarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='status',
            field=models.CharField(choices=[('Reached Out', 'Reached Out'), ('Consideration', 'Consideration'), ('Interview', 'Interview'), ('Offers', 'Offers'), ('Hire', 'Hire')], max_length=255),
        ),
    ]
