# Generated by Django 4.2.5 on 2025-04-07 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cross_dept_app', '0009_alter_candidate_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='status',
            field=models.CharField(blank=True, choices=[('Reached Out', 'Reached Out'), ('Consideration', 'Consideration'), ('Interview', 'Interview'), ('Offers', 'Offers'), ('Hire', 'Hire')], max_length=255, null=True),
        ),
    ]
