# Generated by Django 4.2.5 on 2025-04-08 06:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cross_dept_app', '0010_alter_candidate_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisition',
            name='job_title',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
