# Generated by Django 4.2.5 on 2025-04-08 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cross_dept_app', '0011_requisition_job_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requisition',
            old_name='positions',
            new_name='vacancies',
        ),
    ]
