# Generated by Django 4.2.5 on 2025-04-08 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cross_dept_app', '0012_rename_positions_requisition_vacancies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='source',
            field=models.CharField(blank=True, choices=[('Naukri', 'Naukri'), ('Linkedin', 'Linkedin'), ('Indeed', 'Indeed'), ('Employee Referral', 'Employee Referral')], max_length=100, null=True),
        ),
    ]
