# Generated by Django 4.2.5 on 2025-04-08 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cross_dept_app', '0013_alter_candidate_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisition',
            name='department',
            field=models.CharField(blank=True, choices=[('Administration', 'Administration'), ('Appliance Division', 'Appliance Division'), ('Brand & Communications', 'Brand & Communications'), ('Category Strategy & NBI', 'Category Strategy & NBI'), ('Civil & MEP', 'Civil & MEP'), ('Corporate Manufacturing Services', 'Corporate Manufacturing Services'), ('Customer Service', 'Customer Service'), ('ECDI Service', 'ECDI Service'), ('Electromechanical Division', 'Electromechanical Division'), ('Electronics Division', 'Electronics Division'), ('Emerging Channels & Digital Initiatives', 'Emerging Channels & Digital Initiatives'), ('Finance & Accounts', 'Finance & Accounts'), ('Go To Market', 'Go To Market'), ('Human Resources', 'Human Resources'), ('Industrial Design', 'Industrial Design'), ('IT & Systems', 'IT & Systems'), ('Legal', 'Legal'), ('Marketing', 'Marketing'), ('Mechanical & Electrical Division', 'Mechanical & Electrical Division'), ('New Product Development', 'New Product Development'), ('Quality', 'Quality'), ('R&D (Electronics Division)', 'R&D (Electronics Division)'), ('Strategy', 'Strategy'), ('Supply Chain Management', 'Supply Chain Management'), ('Wires & Cables Division', 'Wires & Cables Division')], max_length=500, null=True),
        ),
    ]
