# Generated by Django 4.2.5 on 2025-04-09 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cross_dept_app', '0014_alter_requisition_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recruiter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('emp_id', models.IntegerField(unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='requisition',
            name='recruiters',
            field=models.ManyToManyField(related_name='requisitions', to='cross_dept_app.recruiter'),
        ),
    ]
