# Generated by Django 4.2.5 on 2025-04-09 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cross_dept_app', '0015_recruiter_requisition_recruiters'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recruiter',
            name='emp_id',
        ),
    ]
