# Generated by Django 4.2.5 on 2025-04-09 11:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cross_dept_app', '0016_remove_recruiter_emp_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requisition',
            name='created_at',
        ),
        migrations.AddField(
            model_name='requisition',
            name='created_on',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
